language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ef78gFZs84iHr0cBCid1wbWGoU41pZBFp/ZqeDkfyhWdCO8hoeWKLgXGSj30lDir+YeYcOBhgAdpWXBdOyjR4jYvnjoht2+5yZD8AJ4mSHcR1etsplxLBKqEVpLFLtCYN6m3oPADa/kJ5PLTSpMoWR05GFkP6vzjqNACDMV9axbneGZUIX94GRyqtS6yGfIFgjh4GHHvxwn4CbZSp1B33mbYuKtrHxM8R/uj0RT3riNaEDsT5iYvlFSq5DWXQRKftDoV1GNDTABnn5+aRupqcCw7y8dIUJTXzMXd66hDqDk0uOK6AgCQiiQ0/RmGu4pfghX25K5EXTzdT29Lpb3BWfF6M+7fpE7p0QRQrtY33Uu7YqVh8Ax5vJ1EvwFVfmjrXpTfQcCx3Inqu2rb/jf7G6aHEG7evWjJ4q9V3nD1mO7ib8TdCecN82VLpWfKsEl0KDj3pd37t8pNH0Dxzzn6gr/rtJjjUQHIU+KPZNyGo7vBkE8BkpQwT+D1y+NlehT2ZhgWWWzki2D71ieEl3RgGWAcb35bV1TACdA00ekCsNwfijz0uEDNrgBACvJiw7omZRiYPZsuL3vAUuRz5QQbBoJf3m7NNxBDq1PULaaZJGtDMCIOV0Um3CuqkKKMKClySlVSJbXpxUQNa06YygFcbcyLzjM/iwo5aQWxLpGeSks=
  app: fathomless-citadel-22031
  on:
    repo: JeffWilkey/blog-api-v2
